apiVersion: v1
kind: Namespace
metadata:
  name: ${{ values.namespace }}
  labels:
    name: ${{ values.namespace }}
    app.kubernetes.io/name: nginx-web-service
    app.kubernetes.io/instance: ${{ values.name }}
    app.kubernetes.io/component: web-server