apiVersion: v1
kind: Namespace
metadata:
  name: ${{ values.namespace }}
  labels:
    app.kubernetes.io/name: ${{ values.name }}
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: ${{ values.name }}-cluster
    name: ${{ values.namespace }}
  annotations:
    description: "MySQL database cluster namespace for ${{ values.name }}"